### ISSUE TITLE
Support for TYPO3 11 LTS

### ISSUE THREAD

**Issue by outdoorsman** [miniOrangeDev/miniorange-saml-typo3-sso#21]
Just adding an issue for this since it was discussed with @sunny-mo in a Google Meeting (so thankful for his help on our project!!!). We are planning an upgrade to TYPO 11 in probably the next 6 months.

TYPO3 11 LTS was in Oct of 2021. Here's a few links on that...

* https://typo3.org/article/typo3-v11-lts-warp-speed
* https://typo3.org/project/press/press-releases/typo3-v11-lts/english
* https://typo3.org/article/typo3-v11-maintenance-release-schedule

**Comment by outdoorsman** [comment]
Just checking in again. I have a client that is wants moving forward with a paid solution from you but need to make sure you're going to continue support TYPO3 onto version 11 and onward?

**Comment by miniOrangeDev** [comment]
Hi, I know it's a bit late, but we have released plugin with v11 support.
