### ISSUE TITLE
Certificates (cert-files) are deprecated

### ISSUE THREAD

**Issue by christianbaer** [miniOrangeDev/miniorange-saml-typo3-sso#3]
The certificated shipped with this extension are either deprecated or about to be invalid.

For example this one:

[/sso/resources/sp-certificate.crt](https://github.com/miniOrangeDev/miniorange-saml-typo3-sso/blob/master/sso/resources/sp-certificate.crt)

is only valid until Oct '20. Could you please ship newer ones? 

Thanks in advance :)

**Comment by christianbaer** [comment]
Hey, any updates on this?

**Comment by miniOrangeDev** [comment]
updated certificates
